/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlCuidador;
import modelo.Cuidador;

/**
 *
 * @author Acer
 */
public class InsertarCuidador extends javax.swing.JFrame {

    /**
     * Creates new form Insertarcuidador
     */
    public InsertarCuidador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jnombrec1 = new javax.swing.JTextField();
        Jnombrec2 = new javax.swing.JTextField();
        Japellidoc2 = new javax.swing.JTextField();
        Japellidoc1 = new javax.swing.JTextField();
        Jtelefonoc1 = new javax.swing.JTextField();
        Jcorreoc = new javax.swing.JTextField();
        Jdireccionc = new javax.swing.JTextField();
        Jtelefonoc2 = new javax.swing.JTextField();
        Jedadc = new javax.swing.JTextField();
        Bagregarcuidador = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Jidcuidador = new javax.swing.JTextField();
        Batrascuidador = new javax.swing.JButton();
        Bcerrarcuidador = new javax.swing.JButton();
        Blimpiarcuidador = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setText("Primer nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 120, 90, 20);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setText("Segundo nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 100, 20);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Primer apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 90, 20);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setText("Segundo apellido");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 210, 100, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel5.setText("Dirección");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 165, 50, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setText("Telefono2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 125, 52, 50);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setText("Telefono1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 105, 52, 30);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("Correo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 240, 50, 20);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setText("Edad");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 200, 30, 15);

        Jnombrec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jnombrec1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jnombrec1);
        Jnombrec1.setBounds(130, 120, 115, 19);

        Jnombrec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jnombrec2ActionPerformed(evt);
            }
        });
        getContentPane().add(Jnombrec2);
        Jnombrec2.setBounds(130, 150, 115, 20);

        Japellidoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Japellidoc2ActionPerformed(evt);
            }
        });
        getContentPane().add(Japellidoc2);
        Japellidoc2.setBounds(130, 210, 115, 20);

        Japellidoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Japellidoc1ActionPerformed(evt);
            }
        });
        getContentPane().add(Japellidoc1);
        Japellidoc1.setBounds(130, 180, 115, 20);

        Jtelefonoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtelefonoc1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jtelefonoc1);
        Jtelefonoc1.setBounds(420, 110, 115, 20);

        Jcorreoc.setToolTipText("");
        Jcorreoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JJcorreocActionPerformed(evt);
            }
        });
        getContentPane().add(Jcorreoc);
        Jcorreoc.setBounds(130, 240, 115, 19);

        Jdireccionc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JdireccioncActionPerformed(evt);
            }
        });
        getContentPane().add(Jdireccionc);
        Jdireccionc.setBounds(420, 170, 115, 20);

        Jtelefonoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtelefonoc2ActionPerformed(evt);
            }
        });
        getContentPane().add(Jtelefonoc2);
        Jtelefonoc2.setBounds(420, 140, 115, 20);

        Jedadc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JedadcActionPerformed(evt);
            }
        });
        getContentPane().add(Jedadc);
        Jedadc.setBounds(420, 200, 115, 20);

        Bagregarcuidador.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Bagregarcuidador.setText("Agregar");
        Bagregarcuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagregarcuidadorActionPerformed(evt);
            }
        });
        getContentPane().add(Bagregarcuidador);
        Bagregarcuidador.setBounds(60, 300, 75, 23);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel10.setText("Identificación ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 90, 90, 15);

        Jidcuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JidcuidadorActionPerformed(evt);
            }
        });
        getContentPane().add(Jidcuidador);
        Jidcuidador.setBounds(130, 90, 115, 19);

        Batrascuidador.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Batrascuidador.setText("Atras");
        Batrascuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatrascuidadorActionPerformed(evt);
            }
        });
        getContentPane().add(Batrascuidador);
        Batrascuidador.setBounds(510, 350, 70, 23);

        Bcerrarcuidador.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Bcerrarcuidador.setText("Cerrar");
        Bcerrarcuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcerrarcuidadorActionPerformed(evt);
            }
        });
        getContentPane().add(Bcerrarcuidador);
        Bcerrarcuidador.setBounds(595, 350, 70, 23);

        Blimpiarcuidador.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Blimpiarcuidador.setText("Limpiar");
        getContentPane().add(Blimpiarcuidador);
        Blimpiarcuidador.setBounds(180, 300, 71, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoologico/insertar cuidador-02.jpg"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 680, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jnombrec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jnombrec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jnombrec1ActionPerformed

    private void Jnombrec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jnombrec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jnombrec2ActionPerformed

    private void Japellidoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Japellidoc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Japellidoc2ActionPerformed

    private void Japellidoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Japellidoc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Japellidoc1ActionPerformed

    private void Jtelefonoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtelefonoc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtelefonoc1ActionPerformed

    private void JJcorreocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JJcorreocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JJcorreocActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void JdireccioncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JdireccioncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JdireccioncActionPerformed

    private void Jtelefonoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtelefonoc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtelefonoc2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void JedadcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JedadcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JedadcActionPerformed

    private void BagregarcuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarcuidadorActionPerformed
     String nombrec1;
     String nombrec2;
     String apellidoc1;
     String apellidoc2;
     int edadc;
     String correoc;
     String telc1;
     String telc2;
     String dirc;
     int id_cuidador;
     
     id_cuidador=Integer.parseInt(Jidcuidador.getText());
     nombrec1=Jnombrec1.getText();
     nombrec2=Jnombrec2.getText();
     apellidoc1=Japellidoc1.getText();
     apellidoc2=Japellidoc2.getText();
     edadc=Integer.parseInt(Jedadc.getText());
     correoc=Jcorreoc.getText();
     telc1=Jtelefonoc1.getText();
     telc2=Jtelefonoc2.getText();
     dirc = Jdireccionc.getText();
     
       ControlCuidador objce=new ControlCuidador();
       Cuidador objc=new Cuidador(id_cuidador,nombrec1,nombrec2,apellidoc1,apellidoc2,edadc,correoc,telc1,telc2,dirc);
        boolean f=objce.insertarCuidador(objc);
        
        if(f){
            
            System.out.println("Se inserto el cuidador");
        }else{
            System.out.println("No se inserto el cuidador");
        }
                                         
    }//GEN-LAST:event_BagregarcuidadorActionPerformed

    private void JidcuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JidcuidadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JidcuidadorActionPerformed

    private void BatrascuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatrascuidadorActionPerformed
        OpcionesInsertar abrir = new OpcionesInsertar();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BatrascuidadorActionPerformed

    private void BcerrarcuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcerrarcuidadorActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BcerrarcuidadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarCuidador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregarcuidador;
    private javax.swing.JButton Batrascuidador;
    private javax.swing.JButton Bcerrarcuidador;
    private javax.swing.JButton Blimpiarcuidador;
    private javax.swing.JTextField Japellidoc1;
    private javax.swing.JTextField Japellidoc2;
    private javax.swing.JTextField Jcorreoc;
    private javax.swing.JTextField Jdireccionc;
    private javax.swing.JTextField Jedadc;
    private javax.swing.JTextField Jidcuidador;
    private javax.swing.JTextField Jnombrec1;
    private javax.swing.JTextField Jnombrec2;
    private javax.swing.JTextField Jtelefonoc1;
    private javax.swing.JTextField Jtelefonoc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
