/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlVeterinario;
import modelo.Veterinario;

/**
 *
 * @author LeslyLC
 */
public class ModificarVeterinario extends javax.swing.JFrame {
    int id_veterinario;
    /**
     * Creates new form ModificarVeterinario
     */
    public ModificarVeterinario() {
        initComponents();
            jNombre1.setEnabled(false);
            jNombre2.setEnabled(false);
            jcorreo.setEnabled(false);
            jtelefono1.setEnabled(false);
            jtelefono2.setEnabled(false);
            jApellido1.setEnabled(false);
            jApellido2.setEnabled(false);
            jDireccion.setEnabled(false);
            jEdad.setEnabled(false);
            this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jcorreo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDireccion = new javax.swing.JTextField();
        jButtonmodificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jNombre1 = new javax.swing.JTextField();
        jNombre2 = new javax.swing.JTextField();
        jtelefono1 = new javax.swing.JTextField();
        jtelefono2 = new javax.swing.JTextField();
        jApellido1 = new javax.swing.JTextField();
        jApellido2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jidveterinario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEdad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jcorreo);
        jcorreo.setBounds(311, 55, 76, 20);

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel12.setText("Dirección");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(216, 140, 46, 17);
        getContentPane().add(jDireccion);
        jDireccion.setBounds(311, 140, 78, 20);

        jButtonmodificar.setText("Modificar");
        jButtonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonmodificar);
        jButtonmodificar.setBounds(144, 271, 75, 23);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel6.setText("Telefono 2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(216, 109, 50, 17);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel7.setText("Apellido 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 140, 47, 17);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel8.setText("Apellido 2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 166, 47, 17);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel9.setText("Edad");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 192, 26, 17);
        getContentPane().add(jNombre1);
        jNombre1.setBounds(107, 81, 76, 20);

        jNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombre2ActionPerformed(evt);
            }
        });
        getContentPane().add(jNombre2);
        jNombre2.setBounds(107, 109, 76, 20);
        getContentPane().add(jtelefono1);
        jtelefono1.setBounds(311, 81, 76, 20);
        getContentPane().add(jtelefono2);
        jtelefono2.setBounds(311, 109, 76, 20);
        getContentPane().add(jApellido1);
        jApellido1.setBounds(107, 140, 78, 20);
        getContentPane().add(jApellido2);
        jApellido2.setBounds(107, 166, 78, 20);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(67, 271, 71, 23);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(225, 271, 75, 23);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel1.setText("Modificar Veterinario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(85, 20, 181, 29);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel4.setText("Id Veterinario");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 55, 63, 17);

        jidveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jidveterinarioActionPerformed(evt);
            }
        });
        getContentPane().add(jidveterinario);
        jidveterinario.setBounds(107, 55, 76, 20);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel2.setText("Nombre 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 81, 49, 17);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel3.setText("Nombre 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 112, 49, 17);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel5.setText("Telefono 1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(216, 81, 50, 17);

        jEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdadActionPerformed(evt);
            }
        });
        getContentPane().add(jEdad);
        jEdad.setBounds(107, 192, 78, 20);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel11.setText("Correo");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(216, 55, 34, 17);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 410, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodificarActionPerformed
        id_veterinario = Integer.parseInt(jidveterinario.getText());
        String nombrev1 = null;
        String nombrev2 = null;
        String apellidov1 = null;
        String apellidov2 = null;
        int edadv = 0;
        String correov = null;
        String telv1 = null;
        String telv2 = null;
        String dirv = null;
     

        if (jNombre2.getText()!=""){
            nombrev2 = jNombre2.getText();
        }

        if (jApellido2.getText()!=""){
            apellidov2 = jApellido2.getText();
        }

        if (jtelefono2.getText()!=""){
            telv2 = jtelefono2.getText();
        }


        nombrev1 = jNombre1.getText();
        apellidov1 = jApellido1.getText();
        edadv = Integer.parseInt(jEdad.getText());
        correov = jcorreo.getText();
        telv1 = jtelefono1.getText();
        dirv = jDireccion.getText();

        ControlVeterinario objm = new ControlVeterinario();

        Veterinario objv=new Veterinario(nombrev1,nombrev2,apellidov1,apellidov2,edadv,correov,telv1,telv2, dirv);

        try {
            boolean ch = objm.ModificarVeterinarios(objv, id_veterinario);
            if (ch){
                System.out.println("Se modificó el veterinario");
            } else {
                System.out.println("No se modificó");
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButtonmodificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int id_veterinario;

        try {

            ControlVeterinario objv = new ControlVeterinario();
            id_veterinario = Integer.parseInt(jidveterinario.getText());
            Veterinario objve = objv.ModificarVeterinario(id_veterinario);
            jNombre1.setText(objve.getNombrev1());
            jNombre2.setText(objve.getNombrev2());
            jcorreo.setText(objve.getCorreov()+ "");
            jtelefono1.setText(objve.getTelv1()+ "");
            jtelefono2.setText(objve.getTelv2()+ "");
            jApellido1.setText(objve.getApellidov1()+ "");
            jApellido2.setText(objve.getApellidov2()+ "");
            jDireccion.setText(objve.getDirv()+ "");
            jEdad.setText(objve.getEdadv()+ "");
            // jXDatePickerlastmodi.setText(obje.getLast_update() + "");

            jNombre1.setEnabled(true);
            jNombre2.setEnabled(true);
            jcorreo.setEnabled(true);
            jtelefono1.setEnabled(true);
            jtelefono2.setEnabled(true);
            jApellido1.setEnabled(true);
            jApellido2.setEnabled(true);
            jDireccion.setEnabled(true);
            jEdad.setEnabled(true);

        } catch (Exception e) {
            System.out.println("error" + e);
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void jidveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jidveterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jidveterinarioActionPerformed

    private void jEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEdadActionPerformed

    private void jNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombre2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField jApellido1;
    private javax.swing.JTextField jApellido2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonmodificar;
    private javax.swing.JTextField jDireccion;
    private javax.swing.JTextField jEdad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNombre1;
    private javax.swing.JTextField jNombre2;
    private javax.swing.JTextField jcorreo;
    private javax.swing.JTextField jidveterinario;
    private javax.swing.JTextField jtelefono1;
    private javax.swing.JTextField jtelefono2;
    // End of variables declaration//GEN-END:variables
}
